sudo: required
language: ruby
services:
- docker
env:
- ROOT_FILE=letter
script:
- docker run --volume "$PWD":/workdir --workdir /workdir tianon/latex latexmk -pdf
  "$ROOT_FILE".tex
before_deploy:
- wget -O pdfsizeopt.single https://raw.githubusercontent.com/pts/pdfsizeopt/master/pdfsizeopt.single
- chmod +x pdfsizeopt.single
- docker run --volume "$PWD":/workdir --workdir /workdir ptspts/pdfsizeopt ./pdfsizeopt.single
  "$ROOT_FILE".pdf "$ROOT_FILE".pdf
- docker run --volume "$PWD":/workdir --workdir /workdir tianon/latex convert -background
  white -alpha remove "$ROOT_FILE".pdf "$ROOT_FILE".png
deploy:
  provider: releases
  api_key:
    secure: uLTjfv0KsY8nZ0brUUTjBBd8sU+vVBdr0CrAxK1sJ6or14M4RZ+gvRZPEF8jLAVsA5k38uWyOIfsFsw6q5FcrdS08rxDPHogQSjC/616BelGxNX0MITX36dGn5G9LNzgMusDu28z7FGs/e2P+7cF+Sunp485a6qpfScfncRLKC9IC6YiCHG15bBhKBX3githELKHgu7PAwoJEH6433xAgX9Xm+LMve/HvLKvdjiv62YyLKcrvL15CQ2aCZ2tHfvJbrUDjPs8I+ryKmHUWMZ1Kmj66HWWrlmWq4LczObDVfZxqHfaLOIEQPi23NtDjfiGHOYbYDSUsoFvUhHJYzM3Z3oKkwLESwRtKPHlT1WLf/SsBM4xCXsriKCuLtInbpxurvW+oMaL+NsROFZ3c0RPGDIpmZtyi15/GLw6iWxZ7JOuP3wZwdKrh9JBswjn8o0klC2yTtbQ6CajY2ygDBlxqQmLxsRuYQGiUjV8oQPvyujM5Umk+GNtywnCE3JkELTbhSxQ+lMM3kvEbqm5qrMJYmJUi8kkEmGR5jrpCBj0t0x1IiUFaO018HL5iARzLmH5rC2H6Lpr3psm7vojsCxwlim+1IK3iki26vvVbFQ3n/wi1Y090f/HEYNJF35Hrdup7CAzuZynXlByysfMauQG+o2kQpXLUyXmHGV+atu6MUc=
  file:
    - $ROOT_FILE.pdf
    - $ROOT_FILE.png
  skip_cleanup: true
  on:
    repo: janmattfeld/latex-briefvorlage
    tags: true
